CXX=clang++-14
CXXFLAGS=-O3 -I. -std=c++20
CXXFLAGS=-O3 -mcpu=neoverse-512tvb -I. -std=c++20

all: minigemm.cpp
	$(CXX) $(CXXFLAGS) $<

highprec: minigemm.cpp
	$(CXX) $(CXXFLAGS) -DHIGHPREC $< -lgmpxx -lgmp -lqd
